slack_notification/slack_deploy_notification.php, slack_notification/slack_sync_notification.php
This adds a script to send the most recent commit to Slack upon code sync, and makes some minor formatting improvements to the original slack_notification.php (now renamed to slack_deploy_notification.php). It also pulls the Slack channel from a slack_channel key in secrets.json, if it exists. This removes all site-specific code from the script, enabling it to be included in an organization's upstream.
=> Added script for Slack notification upon code sync.

slack_notification/slack_deploy_notification.php, slack_notification/slack_sync_notification.php
Converted the example slack deploy and code push notifications to Slack attachments.
Added some lines to make debugging the attachments payload much easier. 
This is a very specific example that I think will work well for 80% of people, but there are more options you could include in slack attachments if you want to build out the example.
=> Slack Attachments & Debugging for better construction of JSON Slack Webhooks

drush_example/README.md, drush_example/drush_example.php
An example that shows drush executed with `shell_exec()` in conjunction with `--format=json` on the drush command, as well as a simple `passthru()`.
=> Drush example

slack_notification/slack_notification.php
Displays "After sync code", for example.
=> Include an indication of the slack notification workflow stage

debugging_example/debug.php
I like to show the environment variables in my debugging scripts.  Any reason why we shouldn't do this in the example?
=> Show environment variables in the debugging example

wp_cfm_import/README.md, wp_cfm_import/alter_wpcfm_config_path.php, wp_cfm_import/wp_cfm_after_clone.php
Use wp-cfm and it's wp-cli integration to automatically import settings after db-clone
=> Example of automatically importing settings for wordpress

drush_config_import/README.md, drush_config_import/drush_config_import.php
This example fulfills #59. Testing this site requires a Drupal 8 site. if you want a fresh site to test with, try copying these commands:
```bash
RAND_SITE=$(date |md5 | head -c12)
echo "Creating a site named: $RAND_SITE"
terminus sites create --site=$RAND_SITE --label=$RAND_SITE --upstream="Drupal 8"
terminus drush --site=$RAND_SITE --env=dev 'si -y'
echo 'sleeping so that the commit is not attempted before the file change is picked up.'  
sleep 10 
terminus site --site=$RAND_SITE   code commit --env=dev --message="Installing drupal"
terminus site init-env --site=$RAND_SITE --env=test
terminus site init-env --site=$RAND_SITE --env=live
```
To test this PR use the following steps. The terminus commands below assume that a site name is being set using a `.env` file rather than using a …
=> Example that imports configuration changes from .yml files upon code deployments

example.pantheon.yml, generate_dev_content/README.md, generate_dev_content/generate_dev_content.php
Here is an example for generating development "article" content on DB clone operations. This is useful if your live site has only a few pieces of content (i.e. an initial blog post), but you need lots of extra content for development purposes.
=> Adding an example for generating development content on DB clones

README.md
Script developers might start by looking for what environment variables are available to them. Highlighting this in the main README may reduce support requests.
=> #105 - Add information on environment variables

db_sanitization/db_sanitization_drupal.php
The previous example bootstrapped D7. It was inflexible and needing to be updated to D8, so I asked @greg-1-anderson . He suggested a pull request to use Drush sql-sanitize instead.
=> Updating the db-sanitization example to use drush

wp_cfm_import/README.md, wp_cfm_import/wp_cfm_after_clone.php
Having to edit the PHP file each time you add new config is cumbersome. This pull request allows all json files in `private/config` to be imported automatically. Import happens on deploy as well as database clone.
=> Import all wp-cfm config files in private/scripts

new_relic_deploy/new_relic_deploy.php
The variable $deploy_tag was changed to $revision in all places but one. I changed the remaining old name to the new name: $revision.
=> Corrected variable name syntax error

new_relic_deploy/new_relic_deploy.php
`git describe --tags` outputs the latest tag but in long format. According to [the docs](https://git-scm.com/docs/git-describe) we can use `--abbrev=0` "to _suppress long format, only showing the closest tag_". This is important because `git tag` prefers the short name.
Closes #124.
=> Use short format when retrieving the latest git tag.

url_checker/url_checker.php
count() method used on top of the $failed variable which is already a valid numeric value.
=> Fixed incorrect $failed URL check count

wp_search_replace/README.md, wp_search_replace/wp_search_replace.php
This Quicksilver example adds automated wp search_replace on db clone in different environments.
This was originally brought up in @alexfornuto 's PR in Docs: [include quicksilver resolution to multiple DB find/replace #3960](https://github.com/pantheon-systems/documentation/pull/3960).
=> Adding the wp_search_replace example

db_sanitization/db_sanitization_drupal.php, db_sanitization/db_sanitization_wordpress.php
This PR fixes two different typos in comments within both the WordPress and Drupal db_sanitization examples.
=> Fix db sanitization typos

quicksilver_pushback/README.md
The Quicksilver Pushback project is an example that I've referenced in Office Hours and training that allows code to be pushed back from Pantheon to the external git repo that it originated from. I always look in the Quicksilver Examples repo, but it's managed in its own repo so that it's able to be pulled in as a dependency. 
This PR adds a folder + readme for this project, but rather than providing the code for the project, it just links to the existing project: https://github.com/pantheon-systems/quicksilver-pushback
=> Adding information about the Quicksilver Pushback project

new_relic_deploy/new_relic_deploy.php
Closes #141 and #155
PR includes the following changes:
- Use the New Relic v2 API (inspired largely by @pingevt in [this issue comment](https://github.com/pantheon-systems/quicksilver-examples/issues/141)).
- Use PHP cURL so we can capture more debugging output and set timeouts.
=> Use New Relic's V2 API for marking deploys

new_relic_deploy/new_relic_deploy.php
Some variables are left undefined if the site is leveraging integrated composer.  Adding wf_type sync_code_with_build to address.
=> Account for wf_type sync_code_with_build for IC sites

new_relic_deploy/new_relic_deploy.php
Fixes a 'bad request' error from the New Relic API, which was causing markers to not be stored in test and live env's (although dev was working) - see support ticket: 929345
The Pantheon internal process that processes the workflow to the test and live env's was using the tag and git commit text for revision and changelog in the demo, which was adding a \n to the end of the git output and apostrophes inline, and causing the deployment markers to be denied by the API
A simple rtrim and replacing apostrophes fixes it, and allows the marker to be created successfully.
=> Cleans up git output for NR API post
