pantheon-systems/quicksilver-examples

slack_notification/slack_deploy_notification.php, slack_notification/slack_lib.inc, slack_notification/slack_sync_notification.php
The other script needs to be refactored, and needs testing, but here's the general idea.
=> Factor out slack_lib, and do better error checking on secrets file.

revert_all_features/README.md, revert_all_features/revert_all_features.php
Made an example of integrating a drush command into a quicksilver operation. This operation will revert all of the features before deploying to test or live.
=> Revert all features

webhook/README.md, webhook/webhook.php
=> Mikemilano webhook

cloudflare_cache/README.md, cloudflare_cache/cloudflare_cache.json, cloudflare_cache/cloudflare_cache.php
Kudos to @mikemilano for this example. Closes #19.
=> Cloudflare

README.md
Copying some troubleshooting tips from this thread. https://github.com/pantheon-systems/quicksilver-examples/issues/24
=> adding 'Troubleshooting' section to README

jira_integration/README.md, jira_integration/jira_integration.json, jira_integration/jira_integration.php
=> Mike Milano jira integration

slack_notification/slack_notification.php
missing 3rd arg for str_replace() - switched . for ,
=> Fix some errors in slack_notification.php

slack_notification/slack_notification.php
per https://pantheon.io/docs/platform-domains/
=> Default to new pantheon site urls

example.pantheon.yml, spotbot_visualregression/README.md, spotbot_visualregression/spotbot_visualregression.php
This is an example Quicksilver integration for Spotbot.qa that will do an automatic visual regression test every-time you deploy to test implementing the REST API documented here (http://docs.spotbot.qa/api.html).
=> Spotbot Visual Regression Quicksilver Integration

backtrac_visualregression/README.md, backtrac_visualregression/backtrac_visualregression.php, example.pantheon.yml
This is an example Quicksilver integration for Backtrac.io that will do an automatic visual regression test every-time you deploy to test implementing the `compare_prod_stage` REST API operation documented here ([http://backtrac.io/documentation/rest-api](http://backtrac.io/documentation/rest-api)).
=> Backtrac.io Visual Regression Quicksilver Integration

README.md
=> Readme: Add info on when updates take effect

backtrac_visualregression/backtrac_visualregression.php
A couple updates to the example: 
- Added information about storing the API key in the private directory of the file system=
- Updating API Call to Use New HTTPS Endpoint
=> Update to Backtrac Quicksilver Example

new_relic_deploy/README.md
Align `new_relic_deploy/README.md` with New Relic Pro product release
cc @nataliejeremy
=> Update New Relic Deploy Logs

slack_notification/README.md
=> Add new hooks to Slack example README

example.pantheon.yml
- Nested DOCROOT (web_root)
- protected_web_paths
- php_version
New Quicksilver Hooks:
* Site creation (deploy_product)
* Multidev creation (create_cloud_development_environment)
< Hold for release >
=> Add new features to example.pantheon.yml

new_relic_apdex_t/README.md, new_relic_apdex_t/new_relic_apdex_t.php
Fulfills https://github.com/pantheon-systems/quicksilver-examples/issues/86
=> Set Apdex T values on multidev creation

new_relic_deploy/new_relic_deploy.php
=> Fix spelling of "snippet" in new_relic_deploy

chikka-sms-notification/README.md, chikka-sms-notification/chikka_sms_notification.php, chikka-sms-notification/example_pantheon.yml
Adding SMS Notification using Chikka API
=> Adding SMS Notification using Chikka API

slack_notification/slack_notification.php
Added notification for site cache clearing.
Deploy note formatting wasn't working so moved it into a pane.
=> Tweaked deploy note, cache notification added

drush_config_import/drush_config_import.php
A correction via @thejimbirch in a Pantheon Training at Twin Cities Drupal Camp.
=> drush cr for Drupal 8

url_checker/url_checker.php
Fixed the isset() function in URL checker example.
=> Call to undefined function is_set() in url_checker.php

jenkins/jenkins_integration.php
Discussed with @greg-1-anderson, fixes "Trying to get property of non-object" PHP error.
=> Get array values, not object properties

trello_integration/README.md, trello_integration/trello_integration.php
Implementation of Trello script as used for the integration guide; based on the existing Jira script.
=> Trello Integration

pivotal-tracker/README.md, pivotal-tracker/pivotal_integration.php
Hey @greg-1-anderson Here is a QS script for Pivotal Tracker, for use with a forthcoming guide. It's mostly your Jira guide and tested on a site and PT instance I spun up.
=> Pivotal tracker

asana_integration/README.md, asana_integration/asana_integration.php
Implementation of Asana script as used for the integration guide (see https://github.com/pantheon-systems/documentation/pull/2732).
=> Asana Integration implementation

asana_integration/asana_integration.php, chikka-sms-notification/chikka_sms_notification.php, cloudflare_cache/cloudflare_cache.php, hipchat_notification/hipchat_notification.php, jenkins/jenkins_integration.php, jira_integration/jira_integration.php, new_relic_deploy/new_relic_deploy.php, pivotal-tracker/pivotal_integration.php, slack_notification/slack_notification.php, trello_integration/trello_integration.php
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
=> Change PHP keywords to comply with PSR2

diffy_visualregression/diffyVisualregression.php
Instead of using login/password we switch to using authentication keys.
=> Diffy testing. Switch to using Key for authentication.

db_sanitization/README.md, new_relic_deploy/README.md
I came across some typos when presenting Quicksilver demos recently. This is almost definitely not all of the instances of this bug, but these are the two examples that I look at most often during training.
=> Quicksilver typos

diffy_visualregression/diffyVisualregression.php
There were some changes in the parameters of the comparison call.
Also, our URLs changed slightly.
=> Environment parameters. Preview no more "ui" in path.

teams_notification/README.md, teams_notification/samples/clear_cache_msg.json, teams_notification/samples/deploy_msg.json, teams_notification/samples/sync_code_msg.json, teams_notification/teams_notification.php
This implementation enables notifications to Microsoft Teams for any new commit or deployment on a Pantheon site.
=> Teams Integration implementation

autopilot/README.md, autopilot/autopilot.json, autopilot/autopilot.php
This PR adds an example Slack + Autopilot Quicksilver example.
=> Add autopilot example

debugging_example/debug.php, url_checker/url_checker.php
Sorry about the combined pull requests. I forgot to create new local branches for the first two...
-mike
=> Pantheon url bug

debugging_example/debug.php, url_checker/url_checker.php
=> Minor typo fix.

google_chat_notification/README.md, google_chat_notification/google_chat_notification.php
Adds integration with Google Chat using their Incoming Webhook integation. https://developers.google.com/chat/how-tos/webhooks
=> Add Google Chat integration

new_relic_apdex_t/new_relic_apdex_t.php, new_relic_deploy/new_relic_deploy.php, new_relic_monitor/new_relic_monitor.php
The app name for new relic can be found accurately in the ini config. Switched the source of `app_name` to `init_get`.
=> Updated the new relic app name configuration source.

new_relic_deploy/new_relic_deploy.php
This PR introduces the following changes:
- Replaces the REST API call with a GraphQL query.
- To transitioning away from the legacy REST API we need to use your application’s entity GUID instead of the appID for API interactions.
- Introduces the changeTrackingCreateDeployment mutation to track deployment changes.
References:
[NerdGraph Entities API Tutorial](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial/)
[Change Tracking with GraphQL](https://docs.newrelic.com/docs/change-tracking/change-tracking-graphql/)
Jenkins job link: https://35.184.37.86:8090/jenkins/job/endpoint_quicksilver/768/console
=> fix(SITE-2575): Updates restapi call to graphql.
